name = "LyoPronto"
uuid = "86014da0-a5b3-40a4-ad76-3e66dfc3e269"
authors = ["Isaac Wheeler <ickaser@gmail.com>"]
version = "0.3.1"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
ConstructionBase = "187b0558-2788-49d3-abe0-74a17ed4e7c9"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SavitzkyGolay = "c4bf5708-b6a6-4fbe-bcd0-6850ed671584"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
TransformVariables = "84d833dd-6860-57f9-a1a7-6da5db126cff"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ADTypes = "1.14"
Accessors = "0.1"
CSV = "0.10"
ColorTypes = "0.11.2, 0.12"
ConcreteStructs = "0.2.3"
ConstructionBase = "1"
DataInterpolations = "7.2, 8"
DiffEqCallbacks = "3, 4"
DocStringExtensions = "0.9"
LinearAlgebra = "1"
OrdinaryDiffEqNonlinearSolve = "1"
OrdinaryDiffEqRosenbrock = "1"
PrecompileTools = "1"
RecipesBase = "1"
Reexport = "1"
Roots = "2"
SavitzkyGolay = "0.9.1"
SpecialFunctions = "1, 2"
TransformVariables = "0.8.19"
Unitful = "1.20"
julia = "1.10"
